// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/amm/v1beta1/amm.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Pool struct {
	Id          uint64                                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token1      types.Coin                             `protobuf:"bytes,3,opt,name=token1,proto3" json:"token1"`
	Token2      types.Coin                             `protobuf:"bytes,4,opt,name=token2,proto3" json:"token2"`
	Fee         github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=fee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"fee"`
	Creator     string                                 `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	TotalShares github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,7,opt,name=totalShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"totalShares"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_10adc5b3f0180f44, []int{0}
}
func (m *Pool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return m.Size()
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pool) GetToken1() types.Coin {
	if m != nil {
		return m.Token1
	}
	return types.Coin{}
}

func (m *Pool) GetToken2() types.Coin {
	if m != nil {
		return m.Token2
	}
	return types.Coin{}
}

func (m *Pool) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type PoolShare struct {
	Address string                                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Shares  github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=shares,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"shares"`
}

func (m *PoolShare) Reset()         { *m = PoolShare{} }
func (m *PoolShare) String() string { return proto.CompactTextString(m) }
func (*PoolShare) ProtoMessage()    {}
func (*PoolShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_10adc5b3f0180f44, []int{1}
}
func (m *PoolShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolShare.Merge(m, src)
}
func (m *PoolShare) XXX_Size() int {
	return m.Size()
}
func (m *PoolShare) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolShare.DiscardUnknown(m)
}

var xxx_messageInfo_PoolShare proto.InternalMessageInfo

func (m *PoolShare) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PoolShare) GetShares() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Shares
	}
	return nil
}

type Params struct {
	SwapAllowedTokens []string                               `protobuf:"bytes,1,rep,name=swap_allowed_tokens,json=swapAllowedTokens,proto3" json:"swap_allowed_tokens,omitempty"`
	MaxSwapFee        github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=max_swap_fee,json=maxSwapFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_swap_fee"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_10adc5b3f0180f44, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSwapAllowedTokens() []string {
	if m != nil {
		return m.SwapAllowedTokens
	}
	return nil
}

func init() {
	proto.RegisterType((*Pool)(nil), "cosmos.amm.v1beta1.Pool")
	proto.RegisterType((*PoolShare)(nil), "cosmos.amm.v1beta1.PoolShare")
	proto.RegisterType((*Params)(nil), "cosmos.amm.v1beta1.Params")
}

func init() { proto.RegisterFile("cosmos/amm/v1beta1/amm.proto", fileDescriptor_10adc5b3f0180f44) }

var fileDescriptor_10adc5b3f0180f44 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x6b, 0xd4, 0x40,
	0x18, 0xcd, 0x64, 0x63, 0xca, 0x4e, 0x45, 0xe8, 0x28, 0x98, 0x16, 0x49, 0x96, 0x22, 0x12, 0x0a,
	0x26, 0xec, 0x8a, 0x08, 0x3d, 0xe9, 0x2a, 0x82, 0xb7, 0x25, 0xf5, 0xe4, 0x65, 0x99, 0x4d, 0xc6,
	0xdd, 0xd0, 0x9d, 0x7c, 0x21, 0x33, 0xba, 0xeb, 0xbf, 0xe0, 0xc9, 0x8b, 0xe0, 0xb1, 0x47, 0xf1,
	0xb4, 0x7f, 0x46, 0x8f, 0x7b, 0x14, 0x0f, 0x55, 0x76, 0x0f, 0xf5, 0xcf, 0x90, 0xf9, 0xb1, 0xa5,
	0xa7, 0x62, 0x7b, 0x49, 0x66, 0xbe, 0xf7, 0xbd, 0xf7, 0xbd, 0x79, 0x93, 0xe0, 0x07, 0x39, 0x08,
	0x0e, 0x22, 0xa5, 0x9c, 0xa7, 0x1f, 0xbb, 0x23, 0x26, 0x69, 0x57, 0xad, 0x93, 0xba, 0x01, 0x09,
	0x84, 0x18, 0x34, 0x51, 0x15, 0x8b, 0xee, 0xdd, 0x1b, 0xc3, 0x18, 0x34, 0x9c, 0xaa, 0x95, 0xe9,
	0xdc, 0x0b, 0xad, 0xce, 0x88, 0x0a, 0x76, 0x21, 0x94, 0x43, 0x59, 0x59, 0x7c, 0xd7, 0xe0, 0x43,
	0x43, 0xb4, 0xb2, 0x06, 0xda, 0xa1, 0xbc, 0xac, 0x20, 0xd5, 0x4f, 0x53, 0xda, 0x5f, 0xba, 0xd8,
	0x1b, 0x00, 0x4c, 0xc9, 0x1d, 0xec, 0x96, 0x45, 0x80, 0x3a, 0x28, 0xf6, 0x32, 0xb7, 0x2c, 0x08,
	0xc1, 0x5e, 0x45, 0x39, 0x0b, 0xdc, 0x0e, 0x8a, 0xdb, 0x99, 0x5e, 0x93, 0x67, 0xd8, 0x97, 0x70,
	0xcc, 0xaa, 0x6e, 0xd0, 0xea, 0xa0, 0x78, 0xbb, 0xb7, 0x9b, 0x58, 0x79, 0xe5, 0x65, 0x63, 0x3b,
	0x79, 0x09, 0x65, 0xd5, 0xf7, 0x4e, 0xcf, 0x22, 0x27, 0xb3, 0xed, 0x17, 0xc4, 0x5e, 0xe0, 0x5d,
	0x87, 0xd8, 0x23, 0xcf, 0x71, 0xeb, 0x3d, 0x63, 0xc1, 0x2d, 0x65, 0xa2, 0x9f, 0x28, 0xe8, 0xd7,
	0x59, 0xf4, 0x68, 0x5c, 0xca, 0xc9, 0x87, 0x51, 0x92, 0x03, 0xb7, 0xe7, 0xb3, 0xaf, 0xc7, 0xa2,
	0x38, 0x4e, 0xe5, 0xa7, 0x9a, 0x89, 0xe4, 0x15, 0xcb, 0x33, 0x45, 0x25, 0x01, 0xde, 0xca, 0x1b,
	0x46, 0x25, 0x34, 0x81, 0xaf, 0x8f, 0xb2, 0xd9, 0x92, 0x01, 0xde, 0x96, 0x20, 0xe9, 0xf4, 0x68,
	0x42, 0x1b, 0x26, 0x82, 0xad, 0x6b, 0xcf, 0x78, 0x53, 0xc9, 0xec, 0xb2, 0xc4, 0xa1, 0xf7, 0xf7,
	0x24, 0x42, 0xfb, 0x5f, 0x11, 0x6e, 0xab, 0x48, 0x75, 0x51, 0xcd, 0xa7, 0x45, 0xd1, 0x30, 0x21,
	0x74, 0xb8, 0xed, 0x6c, 0xb3, 0x25, 0x13, 0xec, 0x0b, 0x33, 0xda, 0xed, 0xb4, 0xae, 0x0e, 0xe5,
	0xa9, 0x72, 0xf5, 0xe3, 0x77, 0x14, 0xff, 0x87, 0x2b, 0x45, 0x10, 0xdf, 0xcf, 0x17, 0x07, 0x28,
	0xb3, 0xfa, 0xd6, 0xd7, 0x02, 0x61, 0x7f, 0x40, 0x1b, 0xca, 0x05, 0x49, 0xf0, 0x5d, 0x31, 0xa3,
	0xf5, 0x90, 0x4e, 0xa7, 0x30, 0x63, 0xc5, 0x50, 0xa7, 0xad, 0x0c, 0xb6, 0xe2, 0x76, 0xb6, 0xa3,
	0xa0, 0x17, 0x06, 0x79, 0xab, 0x01, 0x32, 0xc0, 0xb7, 0x39, 0x9d, 0x0f, 0x35, 0x47, 0xdd, 0x87,
	0x7b, 0xa3, 0xfb, 0xc0, 0x9c, 0xce, 0x8f, 0x66, 0xb4, 0x7e, 0xcd, 0xd8, 0xe1, 0xc3, 0x6f, 0x27,
	0x91, 0xa3, 0x6c, 0x7d, 0x3e, 0x5f, 0x1c, 0xdc, 0xbf, 0xd4, 0x3e, 0xd7, 0x3f, 0x88, 0xf1, 0xd9,
	0xef, 0x9f, 0xae, 0x42, 0xb4, 0x5c, 0x85, 0xe8, 0xcf, 0x2a, 0x44, 0x5f, 0xd6, 0xa1, 0xb3, 0x5c,
	0x87, 0xce, 0xcf, 0x75, 0xe8, 0xbc, 0xbb, 0x3a, 0x09, 0x23, 0xa2, 0x27, 0x8f, 0x7c, 0xfd, 0xa1,
	0x3f, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x00, 0x25, 0x56, 0x5a, 0x80, 0x03, 0x00, 0x00,
}

func (this *Pool) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Pool)
	if !ok {
		that2, ok := that.(Pool)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if !this.Token1.Equal(&that1.Token1) {
		return false
	}
	if !this.Token2.Equal(&that1.Token2) {
		return false
	}
	if !this.Fee.Equal(that1.Fee) {
		return false
	}
	if this.Creator != that1.Creator {
		return false
	}
	if !this.TotalShares.Equal(that1.TotalShares) {
		return false
	}
	return true
}
func (this *PoolShare) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PoolShare)
	if !ok {
		that2, ok := that.(PoolShare)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if len(this.Shares) != len(that1.Shares) {
		return false
	}
	for i := range this.Shares {
		if !this.Shares[i].Equal(&that1.Shares[i]) {
			return false
		}
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.SwapAllowedTokens) != len(that1.SwapAllowedTokens) {
		return false
	}
	for i := range this.SwapAllowedTokens {
		if this.SwapAllowedTokens[i] != that1.SwapAllowedTokens[i] {
			return false
		}
	}
	if !this.MaxSwapFee.Equal(that1.MaxSwapFee) {
		return false
	}
	return true
}
func (m *Pool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAmm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAmm(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.Fee.Size()
		i -= size
		if _, err := m.Fee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAmm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Token2.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAmm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Token1.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAmm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintAmm(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintAmm(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PoolShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Shares) > 0 {
		for iNdEx := len(m.Shares) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Shares[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAmm(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintAmm(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxSwapFee.Size()
		i -= size
		if _, err := m.MaxSwapFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintAmm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.SwapAllowedTokens) > 0 {
		for iNdEx := len(m.SwapAllowedTokens) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SwapAllowedTokens[iNdEx])
			copy(dAtA[i:], m.SwapAllowedTokens[iNdEx])
			i = encodeVarintAmm(dAtA, i, uint64(len(m.SwapAllowedTokens[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintAmm(dAtA []byte, offset int, v uint64) int {
	offset -= sovAmm(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovAmm(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAmm(uint64(l))
	}
	l = m.Token1.Size()
	n += 1 + l + sovAmm(uint64(l))
	l = m.Token2.Size()
	n += 1 + l + sovAmm(uint64(l))
	l = m.Fee.Size()
	n += 1 + l + sovAmm(uint64(l))
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAmm(uint64(l))
	}
	l = m.TotalShares.Size()
	n += 1 + l + sovAmm(uint64(l))
	return n
}

func (m *PoolShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAmm(uint64(l))
	}
	if len(m.Shares) > 0 {
		for _, e := range m.Shares {
			l = e.Size()
			n += 1 + l + sovAmm(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SwapAllowedTokens) > 0 {
		for _, s := range m.SwapAllowedTokens {
			l = len(s)
			n += 1 + l + sovAmm(uint64(l))
		}
	}
	l = m.MaxSwapFee.Size()
	n += 1 + l + sovAmm(uint64(l))
	return n
}

func sovAmm(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAmm(x uint64) (n int) {
	return sovAmm(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAmm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Token1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Token2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAmm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAmm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PoolShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAmm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Shares = append(m.Shares, types.Coin{})
			if err := m.Shares[len(m.Shares)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAmm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAmm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAmm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapAllowedTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapAllowedTokens = append(m.SwapAllowedTokens, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSwapFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxSwapFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAmm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAmm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAmm(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAmm
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAmm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAmm
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAmm
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAmm
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAmm        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAmm          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAmm = fmt.Errorf("proto: unexpected end of group")
)
