syntax = "proto3";
package cosmos.amm.v1beta1;

import "gogoproto/gogo.proto";
import "cosmos/base/v1beta1/coin.proto";
import "cosmos_proto/cosmos.proto";
import "amino/amino.proto";

option go_package = "github.com/cosmos/cosmos-sdk/x/amm/types";

message Pool {
  option (gogoproto.equal) = true;

  uint64 id = 1;

  cosmos.base.v1beta1.Coin token1 = 2[(gogoproto.nullable) = false];

  cosmos.base.v1beta1.Coin token2 = 3[(gogoproto.nullable) = false];

  string fee = 4 [(gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (gogoproto.nullable) = false];

  string creator = 5;

  string totalShares = 6 [(gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (gogoproto.nullable) = false];
}

message PoolShare {
  option (gogoproto.equal) = true;

  string address = 1;

  repeated cosmos.base.v1beta1.DecCoin shares = 2 [(gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.DecCoins", (gogoproto.nullable)     = false, (amino.dont_omitempty)   = true];
}

message Params {
  option (amino.name) = "cosmos-sdk/x/amm/Params";
  option (gogoproto.goproto_stringer) = false;
  option (gogoproto.equal) = true;

  uint32 fee_distribution_period = 1;
}
