syntax = "proto3";
package cosmos.amm.v1beta1;

import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/amm/v1beta1/amm.proto";
import "cosmos_proto/cosmos.proto";

option go_package = "github.com/cosmos/cosmos-sdk/x/amm/types";

service Query {

  rpc Pool(QueryPoolRequest) returns (QueryPoolResponse) {
    option (google.api.http).get = "/cosmos/amm/v1beta1/allPools";
  }

  rpc Parameters(QueryParametersRequest) returns (QueryParametersResponse) {
    option (google.api.http).get = "/cosmos/amm/v1beta1/parameters";
  }
}

// QueryValidatorsRequest is request type for Query/Validators RPC method.
//message QueryAddressRequest {
//  string address = 1;
//}

// QueryValidatorsResponse is response type for the Query/Validators RPC method
//message QueryAddressResponse {
//  // validators contains all the queried validators.
//  UserMessage user_message = 1 [(gogoproto.nullable) = false];
//
//}


message QueryPoolRequest {
  uint64 poolId = 1;
}

message QueryPoolResponse {
  Pool pool = 1 [(gogoproto.nullable) = false];
}

message QueryParametersRequest {}

message QueryParametersResponse {

  Params params = 1 [(gogoproto.nullable) = false];
}
