syntax = "proto3";
package cosmos.amm.v1beta1;

import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "cosmos/amm/v1beta1/amm.proto";
import "cosmos_proto/cosmos.proto";
import "amino/amino.proto";

option go_package = "github.com/cosmos/cosmos-sdk/x/amm/types";

service Query {

  rpc Pool(QueryPoolRequest) returns (QueryPoolResponse) {
    option (google.api.http).get = "/cosmos/amm/v1beta1/pool/{poolId}";
  }

  rpc PoolShares(QueryPoolSharesRequest) returns (QueryPoolSharesResponse) {
    option (google.api.http).get = "/cosmos/amm/v1beta1/poolShare/{address}";
  }

  rpc Parameters(QueryParametersRequest) returns (QueryParametersResponse) {
    option (google.api.http).get = "/cosmos/amm/v1beta1/parameters";
  }
}

message QueryPoolRequest {
  uint64 poolId = 1;
}

message QueryPoolResponse {
  Pool pool = 1 [(gogoproto.nullable) = false];
}

message QueryPoolSharesRequest {
  string address = 1;
  cosmos.base.query.v1beta1.PageRequest pagination = 2;
}

message QueryPoolSharesResponse {

  repeated PoolShare poolShares = 1 [(gogoproto.nullable) = false, (amino.dont_omitempty) = true];

  cosmos.base.query.v1beta1.PageResponse pagination = 2;

}


message QueryParametersRequest {}

message QueryParametersResponse {

  Params params = 1 [(gogoproto.nullable) = false];
}
